#!/usr/bin/env bash
# gen_header.sh — compile both demo shaders to SPIR-V and emit shader_spv.h
# (uint32_t arrays, aligned for vkCreateShaderModule's pCode).
# Committed demo/shader_spv.h is generated; regenerate after shader changes.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
G=/opt/vulkan-sdk/bin/glslangValidator
[ -x "$G" ] || G=glslangValidator

"$G" --target-env vulkan1.2 -S comp "$HERE/shader.comp"      -o "$HERE/shader.spv"
"$G" --target-env vulkan1.2 -S comp "$HERE/shader_const.comp" -o "$HERE/shader_const.spv"

python3 - "$HERE/shader.spv" "$HERE/shader_const.spv" > "$HERE/shader_spv.h" <<'PY'
import struct, sys

def words(path):
    d = open(path, 'rb').read()
    assert len(d) % 4 == 0
    return struct.unpack('<%dI' % (len(d)//4), d)

def emit(name, path):
    w = words(path)
    print(f'const unsigned int {name}[] = {{')
    for i in range(0, len(w), 8):
        print('    ' + ', '.join(str(x) for x in w[i:i+8]) + ',')
    print('};')
    print(f'const unsigned long {name}_len = sizeof({name});')
    print()

print('/* GENERATED by gen_header.sh from shader.comp + shader_const.comp */')
emit('shader_spv',      sys.argv[1])
emit('shader_const_spv', sys.argv[2])
PY
echo "wrote shader.spv / shader_const.spv / shader_spv.h"
